language: ruby
sudo: required
before_script:
  -"rake db:migrate RAILS_ENV=test"

rvm:
 - "2.0.0"
 - rbx

notifications:
  email: false
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

