language: ruby
sudo: required
before_script:
  - "rake db:migrate RAILS_ENV=test"

rvm:
 - "2.0.0"
 - rbx

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database oversized_load_test' -U postgres

notifications:
  email: false
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

